# Generated by Django 3.2.8 on 2021-11-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='https://www.kindpng.com/picc/m/451-4517876_default-profile-hd-png-download.png', null=True, upload_to=''),
        ),
    ]
